name: ch32v00x
version: '0.1'
summary: ch32v00x build and debug tools
description: |
  This snap includes all the tools necessary to develop on ch32v00x MCUs. It includes
  the compiler chain (gcc), the firmware library, open OCD as well as few helper 
  scripts.

base: core22
confinement: strict 

apps:
  addr2line:
    command: usr/bin/riscv-none-elf-addr2line
    plugs:
      - home

  ar:
    command: usr/bin/riscv-none-elf-ar
    plugs:
      - home

  as:
    command: usr/bin/riscv-none-elf-as
    plugs:
      - home

  cplusplus: # FIXME: c++
    command: usr/bin/riscv-none-elf-cplusplus # c++
    plugs:
      - home

  cplusplus-filt: # FIXME c++filt
    command: usr/bin/riscv-none-elf-cplusplusfilt
    plugs:
      - home

  cpp:
    command: usr/bin/riscv-none-elf-cpp
    plugs:
      - home

  elfedit:
    command: usr/bin/riscv-none-elf-elfedit
    plugs:
      - home

  gplusplus: # FIXME g++
    command: usr/bin/riscv-none-elf-gplusplus # g++
    plugs:
      - home

  gcc:
    command: usr/bin/riscv-none-elf-gcc
    plugs:
      - home

  gcc-ar:
    command: usr/bin/riscv-none-elf-gcc-ar
    plugs:
      - home

  gcc-nm:
    command: usr/bin/riscv-none-elf-gcc-nm
    plugs:
      - home

  gcc-ranlib:
    command: usr/bin/riscv-none-elf-gcc-ranlib
    plugs:
      - home

  gcov:
    command: usr/bin/riscv-none-elf-gcov
    plugs:
      - home

  gcov-dump:
    command: usr/bin/riscv-none-elf-gcov-dump
    plugs:
      - home

  gcov-tool:
    command: usr/bin/riscv-none-elf-gcov-tool
    plugs:
      - home

  gprof:
    command: usr/bin/riscv-none-elf-gprof
    plugs:
      - home

  ld:
    command: usr/bin/riscv-none-elf-ld
    plugs:
      - home

  ld-bfd: # FIXME ld.bfd
    command: usr/bin/riscv-none-elf-ld.bfd
    plugs:
      - home

  lto-dump:
    command: usr/bin/riscv-none-elf-lto-dump
    plugs:
      - home

  nm:
    command: usr/bin/riscv-none-elf-nm
    plugs:
      - home

  objcopy:
    command: usr/bin/riscv-none-elf-objcopy
    plugs:
      - home

  objdump:
    command: usr/bin/riscv-none-elf-objdump
    plugs:
      - home

  ranlib:
    command: usr/bin/riscv-none-elf-ranlib
    plugs:
      - home

  readelf:
    command: usr/bin/riscv-none-elf-readelf
    plugs:
      - home

  size:
    command: usr/bin/riscv-none-elf-size
    plugs:
      - home

  strings:
    command: usr/bin/riscv-none-elf-strings
    plugs:
      - home

  strip:
    command: usr/bin/riscv-none-elf-strip
    plugs:
      - home

  gdb:
    command: usr/bin/riscv-none-elf-gdb
    plugs:
      - home

  gdb-add-index:
    command: usr/bin/riscv-none-elf-gdb-add-index
    plugs:
      - home

  run:
    command: usr/bin/riscv-none-elf-run
    plugs:
      - home

  example:
    command: usr/riscv-none-elf/share/example.sh
    completer: usr/riscv-none-elf/share/example.comp.sh
    plugs:
      - home

  openocd:
    command: usr/bin/openocd
    plugs:
      - home
      - hardware-observe
      - raw-usb
      - network-bind
  
  setup-udev:
    command: usr/bin/setup-udev.sh

parts:
  binutils:
    plugin: autotools
    source-type: tar
    source: https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.gz
    override-build: |
      set -eux
      mkdir build
      cd build
      ../configure                          \
        --prefix="/usr"                     \
        --with-build-sysroot="${SNAPCRAFT_STAGE}" \
        --target=riscv-none-elf             \
        --program-prefix=riscv-none-elf-    \
                                            \
        --disable-nls                       \
        --disable-gdb                       \
        --disable-gdbtk                     \
        --disable-sim                       \
        --disable-werror                    \
                                            \
        --enable-initfini-array             \
        --enable-lto                        \
        --enable-plugins                    \
        --enable-build-warnings=no          \
                                            \
        --without-gdb                       \
        --without-x                         \
        --without-tcl                       \
        --without-tk                        \
        --with-system-zlib
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"
      # FIXME Dumb limitation. To be removed when it's fixed (if ever)
      ln -sr ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-c++filt ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-cplusplusfilt
    build-packages:
      - zlib1g-dev
      - texinfo
    stage-packages:
      - zlib1g

  gcc-source:
    plugin: nil
    source: https://gcc.gnu.org/pub/gcc/releases/gcc-12.2.0/gcc-12.2.0.tar.gz
    source-type: tar
    override-pull: |
      craftctl default
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patches/gcc-12.2.0.patch.diff
    override-build: |
      cp --archive --link --no-dereference --update . "${SNAPCRAFT_PART_INSTALL}/gcc"
    prime:
      - -gcc

  newlib-source:
    plugin: nil
    source: http://sourceware.org/pub/newlib/newlib-4.3.0.20230120.tar.gz
    source-type: tar
    override-pull: |
      craftctl default
      patch -p1 < $SNAPCRAFT_PROJECT_DIR/patches/newlib-4.3.0.patch.diff
    override-build: |
      cp --archive --link --no-dereference --update . "${SNAPCRAFT_PART_INSTALL}/newlib"
    prime:
      - -newlib

  gcc:
    after:
      - binutils
      - gcc-source
    plugin: nil
    override-build: |
      ${SNAPCRAFT_STAGE}/gcc/configure CFLAGS="-ffunction-sections -fdata-sections -O2" \
        --prefix="/usr"                                             \
                                                                    \
        --target=riscv-none-elf                                     \
        --with-multilib-generator="rv32ec_zicsr-ilp32e--"           \
        --with-abi=ilp32e                                           \
        --with-arch=rv32ec_zicsr                                    \
                                                                    \
        --disable-libgomp                                           \
        --disable-libmudflap                                        \
        --disable-libquadmath                                       \
        --disable-libsanitizer                                      \
        --disable-libssp                                            \
        --disable-nls                                               \
        --disable-shared                                            \
        --disable-threads                                           \
        --disable-tls                                               \
                                                                    \
        --enable-multilib                                           \
        --enable-checking=release                                   \
        --enable-languages=c,c++                                    \
                                                                    \
        --with-newlib                                               \
        --with-gnu-as                                               \
        --with-gnu-ld                                               \
        --with-system-zlib
      make all-gcc -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip-gcc DESTDIR="${SNAPCRAFT_PART_INSTALL}"
      ln -srf ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-c++ ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-cplusplus
      ln -srf ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-g++ ${SNAPCRAFT_PART_INSTALL}/usr/bin/riscv-none-elf-gplusplus
    build-packages:
      - build-essential
      - python-is-python3
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libisl-dev
    stage-packages:
      - libgmp10
      - libmpfr6
      - libmpc3
      - libisl23

  newlib:
    after:
      - gcc
      - newlib-source
    plugin: nil
    build-environment:
      - CFLAGS_FOR_TARGET: "-ffunction-sections -fdata-sections -O2"
    override-build: |
      ${SNAPCRAFT_STAGE}/newlib/configure         \
        --prefix="/usr"                           \
        --target=riscv-none-elf                   \
                                                  \
        --disable-newlib-supplied-syscalls        \
        --disable-nls                             \
                                                  \
        --enable-newlib-io-c99-formats            \
        --enable-newlib-io-long-long              \
        --enable-newlib-io-long-double            \
        --enable-newlib-mb                        \
        --enable-newlib-reent-check-verify        \
        --enable-newlib-register-fini             \
        --enable-newlib-retargetable-locking
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"

  newlib-nano:
    after:
      - gcc
      - newlib-source
    plugin: nil
    build-environment:
      - CFLAGS_FOR_TARGET: "-DPREFER_SIZE_OVER_SPEED -ffunction-sections -fdata-sections -Os -fno-exceptions"
    override-build: |
      ${SNAPCRAFT_STAGE}/newlib/configure         \
        --prefix="/usr"                           \
        --target=riscv-none-elf                   \
                                                  \
        --disable-newlib-fseek-optimization       \
        --disable-newlib-fvwrite-in-streamio      \
        --disable-newlib-supplied-syscalls        \
        --disable-newlib-unbuf-stream-opt         \
        --disable-newlib-wide-orient              \
        --disable-newlib-retargetable-locking     \
        --disable-nls                             \
                                                  \
        --enable-lite-exit                        \
        --enable-newlib-global-atexit             \
        --enable-newlib-nano-formatted-io         \
        --enable-newlib-nano-malloc               \
        --enable-newlib-reent-check-verify        \
        --enable-newlib-reent-small
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}/nano"
    organize:
      nano/usr/riscv-none-elf/include/newlib.h: usr/riscv-none-elf/include/newlib-nano/newlib.h
      nano/usr/riscv-none-elf/lib/libc.a: usr/riscv-none-elf/lib/libc_nano.a
      nano/usr/riscv-none-elf/lib/libg.a: usr/riscv-none-elf/lib/libg_nano.a
      nano/usr/riscv-none-elf/lib/libgloss.a: usr/riscv-none-elf/lib/libgloss_nano.a
      nano/usr/riscv-none-elf/lib/libm.a: usr/riscv-none-elf/lib/libm_nano.a
      nano/usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libc.a: usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libc_nano.a
      nano/usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libg.a: usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libg_nano.a
      nano/usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libgloss.a: usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libgloss_nano.a
      nano/usr/riscv-none-elf/lib/rv32ec_zicsr/ilp32e/libm.a: usr/riscv-none-elf/lib/rv32ec/ilp32e_zicsr/libm_nano.a
    stage:
      - -nano

  libs:
    after:
      - newlib
    plugin: nil
    override-build: |
      # Ugly work-around
      ln -sf "${SNAPCRAFT_STAGE}/usr/riscv-none-elf/" /usr/riscv-none-elf
      ${SNAPCRAFT_STAGE}/gcc/configure CFLAGS="-ffunction-sections -fdata-sections -O2" \
        --prefix="/usr"                                             \
                                                                    \
        --target=riscv-none-elf                                     \
        --with-multilib-generator="rv32ec_zicsr-ilp32e--"           \
        --with-abi=ilp32e                                           \
        --with-arch=rv32ec_zicsr                                    \
                                                                    \
        --disable-libgomp                                           \
        --disable-libmudflap                                        \
        --disable-libquadmath                                       \
        --disable-libsanitizer                                      \
        --disable-libssp                                            \
        --disable-nls                                               \
        --disable-shared                                            \
        --disable-threads                                           \
        --disable-tls                                               \
                                                                    \
        --enable-multilib                                           \
        --enable-checking=release                                   \
        --enable-languages=c++                                      \
                                                                    \
        --with-newlib                                               \
        --with-gnu-as                                               \
        --with-gnu-ld                                               \
        --with-system-zlib
      make all-target-libgcc -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip-target-libgcc DESTDIR="${SNAPCRAFT_PART_INSTALL}"
      make all-target-libstdc++-v3 -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip-target-libstdc++-v3 DESTDIR="${SNAPCRAFT_PART_INSTALL}"
      rm /usr/riscv-none-elf
    build-packages:
      - build-essential
      - python-is-python3
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libisl-dev

  libs-nano:
    after:
      - newlib
    plugin: nil
    override-build: |
      # Ugly work-around
      ln -sf "${SNAPCRAFT_STAGE}/usr/riscv-none-elf/" /usr/riscv-none-elf
      ${SNAPCRAFT_STAGE}/gcc/configure CFLAGS="-ffunction-sections -fdata-sections -Os -fno-exceptions" \
        --prefix="/usr"                                             \
                                                                    \
        --target=riscv-none-elf                                     \
        --with-multilib-generator="rv32ec_zicsr-ilp32e--"           \
        --with-abi=ilp32e                                           \
        --with-arch=rv32ec_zicsr                                    \
                                                                    \
        --disable-libgomp                                           \
        --disable-libmudflap                                        \
        --disable-libquadmath                                       \
        --disable-libsanitizer                                      \
        --disable-libssp                                            \
        --disable-nls                                               \
        --disable-shared                                            \
        --disable-threads                                           \
        --disable-tls                                               \
                                                                    \
        --enable-multilib                                           \
        --enable-checking=release                                   \
        --enable-languages=c++                                      \
        --enable-target-optspace                                    \
                                                                    \
        --with-newlib                                               \
        --with-gnu-as                                               \
        --with-gnu-ld                                               \
        --with-system-zlib
      make all-target-libgcc -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip-target-libgcc DESTDIR="${SNAPCRAFT_PART_INSTALL}/nano"
      make all-target-libstdc++-v3 -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip-target-libstdc++-v3 DESTDIR="${SNAPCRAFT_PART_INSTALL}/nano"
      rm /usr/riscv-none-elf
    build-packages:
      - build-essential
      - python-is-python3
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev
      - libisl-dev
    organize:
      nano/usr/lib/gcc/riscv-none-elf/12.2.0/libgcc.a: usr/lib/gcc/riscv-none-elf/12.2.0/libgcc_nano.a
      nano/usr/lib/gcc/riscv-none-elf/12.2.0/libgcov.a: usr/lib/gcc/riscv-none-elf/12.2.0/libgcov_nano.a
      nano/usr/riscv-none-elf/lib/libstdc++.a: usr/riscv-none-elf/lib/libstdc++_nano.a
      nano/usr/riscv-none-elf/lib/libsupc++.a: usr/riscv-none-elf/lib/libsupc++_nano.a
    stage:
      - -nano

  gdb:
    after:
      - libs
    source: https://ftp.gnu.org/gnu/gdb/gdb-13.1.tar.xz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - "--prefix=/usr"
      - "--target=riscv-none-elf"
    build-packages:
      - libgmp-dev
      - libexpat1-dev
      - liblzma-dev
      - libmpfr-dev
    stage-packages:
      - libgmp10
      - libexpat1
      - liblzma5
      - libmpfr6
    stage:
      - -usr/share/info/

  # FIXME: spostare all'inizio
  openocd:
    source: https://github.com/karlp/openocd-hacks
    source-type: git
    source-branch: mrs-wch-riscv-221010
    plugin: nil
    override-build: |
      ./bootstrap
      ./configure                 \
          --prefix="/usr"         \
          --disable-werror        \
          --disable-ftdi          \
          --disable-stlink        \
          --disable-ti-icdi       \
          --disable-ftdi-oscan1   \
          --disable-ulink         \
          --disable-usb-blaster-2 \
          --disable-usb-blaster   \
          --disable-ft232r        \
          --disable-vsllink       \
          --disable-xds110        \
          --disable-osbdm         \
          --disable-opendous      \
          --disable-armjtagew     \
          --disable-rlink         \
          --disable-aice          \
          --disable-jlink         \
          --disable-buspirate
      make -j"${SNAPCRAFT_PARALLEL_BUILD_COUNT}"
      make install-strip DESTDIR="${SNAPCRAFT_PART_INSTALL}"
    build-packages:
      - pkg-config
      - build-essential
      - autoconf
      - automake
      - libtool
      - libusb-1.0-0-dev
      - libhidapi-dev
    stage-packages:
      - libusb-1.0-0
      - libhidapi-hidraw0

  firmware:
    after:
      - libs
    source: firmware
    source-type: local
    plugin: make

  examples:
    after:
      - libs
    source: examples
    source-type: local
    plugin: nil
    override-build: |
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/usr/riscv-none-elf/share/"
      cp --archive --link --no-dereference --update . "${SNAPCRAFT_PART_INSTALL}/usr/riscv-none-elf/share/"

  scripts:
    source: scripts
    source-type: local
    plugin: nil
    override-build: |
      mkdir -p "${SNAPCRAFT_PART_INSTALL}/usr/bin/"
      cp --archive --link --no-dereference --update . "${SNAPCRAFT_PART_INSTALL}/usr/bin/"
